/**
 * The generated recall blocks in `atlas/decisions/_index.md` and
 * `atlas/evidence/_index.md` (schema §7.1 "Generated recall block", §8
 * marker variant; spec `recall.index-blocks`) — the fourth consumer of the
 * recall index (§4.11).
 *
 * The two atlas indexes are active prompts that say *when* to read into the
 * directory; this block says *what is in it*: one line per decision or
 * evidence entry — date, id, title, and the subjects it bears on (from
 * inverting `subjects`, so the block shows exactly what the hooks would
 * answer) — newest first, under a `recall`-discriminated marker pair so the
 * CLAUDE.md tooling never matches it. The whole file must stay within §7.1's
 * 300-token budget by `check.index-shape`'s OWN estimator (`words × 1.3`,
 * `src/schema/checks/layout.ts`), so the tail collapses to a count line that
 * points at `cortex recall --kind <kind>`.
 *
 * Callers: `cortex scan` and `cortex init`, immediately after
 * `writeRecallIndex` (Rule 6) — never the post-commit tier (atlas is committed
 * content), never a hook, never `cortex validate`. `cortex sync` strips the
 * block before its template comparison (Rule 7, `stripRecallBlock`).
 *
 * Deterministic Core (R-001): sorting and string assembly; one read and at
 * most one write per file; a rerun over identical input writes nothing.
 */
import * as fs from 'fs';
import * as path from 'path';
import { SCHEMA_VERSION } from '../cli/templates.js';
import type { RecallIndex, RecallSubject } from './index.js';

// ---------------------------------------------------------------------------
// Rule 1 — markers
// ---------------------------------------------------------------------------

export const RECALL_BLOCK_START = (v: string): string => `<!-- cortex:recall:start v${v} -->`;
export const RECALL_BLOCK_END = '<!-- cortex:recall:end -->';
/** Rule 2 — the block's first line. */
export const RECALL_BLOCK_HEADING = '**Recorded (generated by `cortex scan`; newest first):**';

export type RecallBlockKind = 'decision' | 'evidence';

/** The two targets, as `[entry kind, .cortex-relative directory]` (Rule 6). */
export const RECALL_BLOCK_TARGETS: ReadonlyArray<readonly [RecallBlockKind, string]> = [
  ['decision', 'atlas/decisions'],
  ['evidence', 'atlas/evidence'],
];

/** Rule 2 — at most this many subjects per line; the rest is ` (+N)`. */
const MAX_REFS_PER_LINE = 4;
/** §7.1 — the `_index.md` budget `check.index-shape` warns above. */
const INDEX_TOKEN_BUDGET = 300;

/**
 * The block region — the start marker (any version) through the end marker —
 * with the one blank line Rule 1 puts before it. `[^\n]*` keeps the match on
 * the marker's own line, like `upsertClaudeMd`'s CLAUDE.md regex.
 */
const BLOCK_RE = /\n?<!-- cortex:recall:start[^\n]*-->\n[\s\S]*?<!-- cortex:recall:end -->\n?/;

/** The file with its block (and the preceding blank line) removed; the identity when there is none. */
export function stripRecallBlock(content: string): string {
  return content.replace(BLOCK_RE, '');
}

/** Rule 1 — the block appended after the file's final newline, preceded by one blank line. */
function joinBlock(outside: string, block: string): string {
  const sep = outside === '' || outside.endsWith('\n') ? '\n' : '\n\n';
  return outside + sep + block + '\n';
}

// ---------------------------------------------------------------------------
// Rules 2–3 — rendering and the budget collapse
// ---------------------------------------------------------------------------

/** The validator's estimator, verbatim (`src/schema/checks/layout.ts`) so the two agree. */
export function estimateIndexTokens(content: string): number {
  return content.split(/\s+/).length * 1.3;
}

/** Rule 2 — every subject key whose list for `kind` holds the id, sorted. */
function subjectsOf(index: RecallIndex, kind: RecallBlockKind, id: string): string[] {
  const list: keyof RecallSubject = kind === 'decision' ? 'decided' : 'evidence';
  const refs: string[] = [];
  for (const [key, subject] of Object.entries(index.subjects)) {
    if (subject[list].includes(id)) refs.push(key);
  }
  return refs.sort();
}

function refsText(refs: string[]): string {
  if (refs.length === 0) return '—';
  const shown = refs.slice(0, MAX_REFS_PER_LINE).join(', ');
  return refs.length > MAX_REFS_PER_LINE ? `${shown} (+${refs.length - MAX_REFS_PER_LINE})` : shown;
}

/** Rule 2 — the entry lines for `kind`, sorted by date descending then id ascending. */
function entryLines(kind: RecallBlockKind, index: RecallIndex): string[] {
  return Object.entries(index.entries)
    .filter(([, entry]) => entry.kind === kind)
    .sort(([idA, a], [idB, b]) => (a.date < b.date ? 1 : a.date > b.date ? -1 : idA < idB ? -1 : idA > idB ? 1 : 0))
    .map(([id, entry]) => `- ${entry.date.slice(0, 10)} ${id} — ${entry.title} · bears on: ${refsText(subjectsOf(index, kind, id))}`);
}

function collapseLine(kind: RecallBlockKind, n: number): string {
  return `- … and ${n} more (\`cortex recall --kind ${kind}\`)`;
}

function assemble(kept: string[], kind: RecallBlockKind, remainder: number): string {
  const lines = [RECALL_BLOCK_START(SCHEMA_VERSION), RECALL_BLOCK_HEADING, ...kept];
  if (remainder > 0) lines.push(collapseLine(kind, remainder));
  lines.push(RECALL_BLOCK_END);
  return lines.join('\n');
}

/**
 * The block for `kind`, or `null` when the index has no entry of that kind
 * (Rule 4). `outsideText` is the file with any previous block removed — the
 * budget is over the complete file (Rule 3): keep the longest newest-first
 * prefix of entry lines for which `outside + block` fits; the remainder
 * collapses to the count line. When not even one line fits, the block is the
 * heading and the collapse line — and if the hand-written text alone is over
 * budget that pre-existing overage stays `check.index-shape`'s to report.
 */
export function renderRecallBlock(kind: RecallBlockKind, index: RecallIndex, outsideText: string): string | null {
  const lines = entryLines(kind, index);
  if (lines.length === 0) return null;
  for (let keep = lines.length; keep >= 0; keep--) {
    const block = assemble(lines.slice(0, keep), kind, lines.length - keep);
    if (estimateIndexTokens(joinBlock(outsideText, block)) <= INDEX_TOKEN_BUDGET) return block;
  }
  return assemble([], kind, lines.length);
}

// ---------------------------------------------------------------------------
// Rules 4–6 — the writer
// ---------------------------------------------------------------------------

export interface RecallBlocksResult {
  /** `.cortex`-relative directories whose `_index.md` was rewritten. */
  written: string[];
  /** Directories whose `_index.md` already carried the right bytes (no write, mtime untouched). */
  unchanged: string[];
  /** Directories missing, or missing their `_index.md` — nothing written, nothing created (Rule 4). */
  skipped: string[];
}

/**
 * Write the generated block into each target's `_index.md` from the compiled
 * `index` (the in-process object `writeRecallIndex` just serialised — the
 * file is not re-read). Only the region between the markers changes; the new
 * content is computed in full and compared to the current bytes before any
 * write (Rule 5).
 */
export function writeRecallIndexBlocks(root: string, index: RecallIndex): RecallBlocksResult {
  const result: RecallBlocksResult = { written: [], unchanged: [], skipped: [] };
  for (const [kind, relDir] of RECALL_BLOCK_TARGETS) {
    const indexPath = path.join(root, '.cortex', ...relDir.split('/'), '_index.md');
    let current: string;
    try {
      current = fs.readFileSync(indexPath, 'utf-8');
    } catch {
      result.skipped.push(relDir);
      continue;
    }
    const outside = stripRecallBlock(current);
    const block = renderRecallBlock(kind, index, outside);
    const next = block === null ? outside : joinBlock(outside, block);
    if (next === current) {
      result.unchanged.push(relDir);
      continue;
    }
    fs.writeFileSync(indexPath, next, 'utf-8');
    result.written.push(relDir);
  }
  return result;
}
